services:
  pulsar:
    image: "apachepulsar/pulsar:3.3.2"
    command: bin/pulsar standalone
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - type: volume
        source: pulsardata
        target: /pulsar/conf
      - type: volume
        source: pulsarconf
        target: /pulsar/conf
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: unless-stopped
    networks:
      - pulsar
  pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.4.0"
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    networks:
      - pulsar

networks:
  pulsar:
    driver: bridge

volumes:
  pulsardata:
  pulsarconf: